// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});

// Handle invalid refresh token errors
supabase.auth.onAuthStateChange((event, session) => {
  if (event === 'TOKEN_REFRESHED') {
    console.log('Token refreshed successfully');
  } else if (event === 'SIGNED_OUT') {
    // Clear any stale auth data
    localStorage.removeItem('supabase.auth.token');
  }
});

// Add error handler for auth errors
const originalRequest = supabase.auth.refreshSession.bind(supabase.auth);
supabase.auth.refreshSession = async () => {
  try {
    return await originalRequest();
  } catch (error: any) {
    if (error?.message?.includes('Refresh Token Not Found') || error?.message?.includes('Invalid Refresh Token')) {
      // Clear invalid session and redirect to login
      await supabase.auth.signOut();
      console.warn('Invalid refresh token detected, clearing session');
    }
    throw error;
  }
};